replicaCount: 1

image:
  repository: inbal345/producer
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

rabbitmq:
  host: "my-rabbitmq"
  port: "5672"
  username: "user"
  password: "2VU5D1rt31"
  queueName: "pc"
  message: "Hello From Rabbit!"
  repeatCount: "20"

producer:
  messageIntervals: "20"

env:
  url: "amqp://user:password@rabbitmq:5672/"
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: { }
tolerations: [ ]
affinity: { }