replicaCount: 1

image:
  repository: inbal345/releaseproducer
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

rabbitmq:
  port: "5672"
  host: "rabbitmq"
 # username: "rabbitmq_user"
  # password: "rabbitmq_password"
  queueName: "pc"
  message: "Hello From Rabbit!"
  repeatCount: "20"
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi

env:
  url: "amqp://user:password@rabbitmq:5672/"
  messageIntervals: "20"

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: { }
tolerations: [ ]
affinity: { }
livenessProbe: null
readinessProbe: null