replicaCount: 1

image:
  repository: inbal345/releaseproducer
  pullPolicy: Always
  tag: "latest"

env:
  messageIntervals: "20"

rabbitmq:
  auth:
    username: "guest"
    password: "guest"
  service:
    port: 5672
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
  host: "rabbitmq"
  port: "5672"
  queueName: "pc"
  message: "Hello From Rabbit!"
  repeatCount: "20"
  #extraEnvVars:
  #  - name: RABBITMQ_SECURE_PASSWORD
  #    value: "no"  # Temporarily disable secure password for testing
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080

# ingress not in use for my deployment
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe: null #temporarly remove
readinessProbe: null #temporarly remove