replicaCount: 1

image:
  repository: inbal345/releaseconsumer
  pullPolicy: "Always"
  tag: "latest"

env:

rabbitmq:
  auth:
    username: "guest"
    password: "guest"
  service:
    port: 5672
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
  host: "rabbitmq"
  port: "5672"
  queueName: "pc"
  message: "Hello From Rabbit!"
  repeatCount: "20"
  #extraEnvVars:
  #  - name: RABBITMQ_SECURE_PASSWORD
  #    value: "no"  # Temporarily disable secure password for testing
ports:
  - name: metrics
    containerPort: 9422 #for metrics reporting
#env:
 # RABBITMQ_URL: "amqp://username:password@my-rabbitmq:5672/"

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

service:
  type: ClusterIP
  port: 8081

consumer:
  metricsPort: 9422

#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: { }
tolerations: [ ]
affinity: { }
livenessProbe: null
readinessProbe: null