apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_URL
              value: "{{ .Values.env.url }}"
            - name: RABBITMQ_HOST
              value: "{{ .Values.rabbitmq.host }}"
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port }}
            - name: RABBITMQ_USER
              value: "{{ .Values.rabbitmq.username }}"
            - name: RABBITMQ_PASSWORD
              value: "{{ .Values.rabbitmq.password }}"
            - name: QUEUE_NAME
              value: "{{ .Values.rabbitmq.queueName }}"
            - name: PRODUCER_INTERVAL
              value: {{ .Values.producer.interval }}